# @package _global_
wandb:
  enabled: true
  project: csc-what-happens-next
  entity: null
  name: null
  tags: []
  notes: ""
  mode: online
  watch: false
  watch_log: gradients
  watch_log_freq: 100
