# @package _global_
ensemble:
  method: weighted_softmax
  weights: auto
  output_csv: ${hydra:runtime.cwd}/submission_ensemble.csv
  models:
    - name: tsm_resnet
      val_npz: ${hydra:runtime.cwd}/outputs/REPLACE_ME_tsm/preds/val.npz
      test_npz: ${hydra:runtime.cwd}/outputs/REPLACE_ME_tsm/preds/test.npz
    - name: videomae_ssv2
      val_npz: ${hydra:runtime.cwd}/outputs/REPLACE_ME_videomae/preds/val.npz
      test_npz: ${hydra:runtime.cwd}/outputs/REPLACE_ME_videomae/preds/test.npz
