# @package _global_
model:
  name: cnn_transformer
  pretrained: false
  num_classes: ${num_classes}
  num_frames: 7
  spatial_tokens_side: 1
  d_model: 512
  num_layers: 4
  num_heads: 8
  mlp_ratio: 2.0
  dropout: 0.1
  attn_dropout: 0.0
  drop_path: 0.1
