# @package _global_
model:
  name: vjepa2
  variant: facebook/vjepa2-vitl-fpc16-256-ssv2
  pretrained: true
  num_classes: ${num_classes}
  freeze_backbone: false
  num_frames: 16
  input_size: 256
  dropout: 0.1
  ignore_mismatched_sizes: true
