defaults:
  - model: tsm_resnet
  - data: default
  - train: default
  - augmentation: default
  - wandb: "off"
  - experiment: track_a_best
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}

num_classes: 33
