# @package _global_
dataset:
  val_dir: ${hydra:runtime.cwd}/processed_data/val2/val
  test_dir: ${hydra:runtime.cwd}/processed_data/val2/test
  submission_output: ${hydra:runtime.cwd}/processed_data/val2/submission_moe.csv

moe:
  output_csv: ${hydra:runtime.cwd}/processed_data/val2/submission_moe.csv
  experts:
    - name: cnn_transformer
      checkpoint: ${hydra:runtime.cwd}/outputs/cnn_tr_s1_cu/best_model.pt
    - name: tsm_resnet
      checkpoint: ${hydra:runtime.cwd}/outputs/tsm_s1_cu/best_model.pt
    - name: tsm_two_stream_gated
      checkpoint: ${hydra:runtime.cwd}/outputs/two_stream_gated_s1_cu/best_model.pt
    - name: cnn_transformer2
      checkpoint: ${hydra:runtime.cwd}/outputs/cnn_tr_s2_cu/best_model.pt
    - name: tsm_resnet2
      checkpoint: ${hydra:runtime.cwd}/outputs/tsm_s2_cu/best_model.pt
    - name: tsm_two_stream_gated2
      checkpoint: ${hydra:runtime.cwd}/outputs/two_stream_gated_s2_cu/best_model.pt
    - name: tsm_resnet34
      checkpoint: ${hydra:runtime.cwd}/outputs/tsm_34_s2_cu/best_model.pt

  combination: val_acc
  calibrate_temperature: true
