# @package _global_
defaults:
  - override /model: videomae

dataset:
  val_dir: ${hydra:runtime.cwd}/processed_data/val2/val
  test_dir: ${hydra:runtime.cwd}/processed_data/val2/test
  submission_output: ${hydra:runtime.cwd}/processed_data/val2/submission_moe_3vjepa_videomae.csv

moe:
  output_csv: ${dataset.submission_output}
  combination: val_acc
  calibrate_temperature: true

  experts:
    - name: vjepa2_best
      checkpoint: ${hydra:runtime.cwd}/outputs/vjepa2_best/best_model.pt
      batch_size: 4
    - name: vjepa2_s3
      checkpoint: ${hydra:runtime.cwd}/outputs/vjepa2_ssv2_s3/best_model.pt
      batch_size: 4
    - name: vjepa2_s4
      checkpoint: ${hydra:runtime.cwd}/outputs/vjepa2_ssv2_s4/best_model.pt
      batch_size: 4
    - name: vjepa2_s5
      checkpoint: ${hydra:runtime.cwd}/outputs/vjepa2_ssv2_s5/best_model.pt
      batch_size: 4
    - name: videomae_ssv2_finetune
      checkpoint: ${hydra:runtime.cwd}/outputs/videomae_ssv2_finetune/best_model.pt
      batch_size: 8
